#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

# if [[ -n "${library_save_cron:-}" ]]; then
#     echo "*** scheduling job: save_library_to_disk"
#     go-cron "$library_save_cron" /usr/local/bin/save_library_to_disk.sh &
#     sleep 2
# fi

# if [[ -n "${library_reload_cron:-}" ]]; then
#     echo "*** scheduling job: load_master_library_db"
#     go-cron "$library_reload_cron" /usr/local/bin/save_library_to_disk.sh && /usr/local/bin/load_master_library_db.sh &
#     sleep 2
# fi

exec wait
